# Generated by Django 2.1 on 2018-11-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.CharField(choices=[('COMPUTER SCIENCE', 'Computer Science'), ('MARKETING', 'Maarketing'), ('HOSPITAILTY', 'Hospitality')], default='COMPUTER SCIENCE', max_length=9),
        ),
    ]
