# Generated by Django 2.1 on 2018-11-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.CharField(choices=[('ICS', 'ics'), ('MARKETING', 'Marketing'), ('HOSPITAILTY', 'Hospitality')], default='ICS', max_length=9),
        ),
    ]
