# Generated by Django 2.1 on 2018-11-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181101_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.CharField(choices=[('COMPUTER SCIENCE', 'Computer Science'), ('MARKETING', 'Marketing'), ('HOSPITAILTY', 'Hospitality')], default='COMPUTER SCIENCE', max_length=20),
        ),
    ]
