# Generated by Django 2.1 on 2018-11-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181101_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(default='Computer Science', max_length=30),
        ),
    ]
